apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-da-belzinha
  labels:
    app: belzinha
spec:
  replicas: 2
  selector:
    matchLabels:
      app: belzinha
  template:
    metadata:
      labels:
        app: belzinha
    spec:
      containers:
        - name: webserverapi
          image: mateusclira/api-da-belzinha:v5
          ports:
          - containerPort: 8087