apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mateuscliraca
spec:
  dnsNames:
    - www.mateusebelzinha.com.br
  secretName: mateuscliratls
  issuerRef:
    name: letsencrypt-cluster-issuer
    kind: ClusterIssuer