kind: Service
apiVersion: v1
metadata:
  annotations: 
    cloud.google.com/neg: "{\"ingress\":false}"
  name: svc
spec: 
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8087
  selector:
    app: belzinha